import {
  Project,
  WeeklyReport,
  Issue,
  MaterialBoard,
  BudgetItem,
  Document,
  Approval,
  ContractorQuote,
  User,
  RoomMaterialBoard,
} from "./types";

export const MOCK_USERS: User[] = [
  {
    id: "user_1",
    name: "Alexander Weber",
    email: "client@example.com",
    role: "client",
    phone: "+49 89 1234567",
    country: "Germany",
    avatar: "",
  },
  {
    id: "user_2",
    name: "TECTA Admin",
    email: "admin@tecta.cy",
    role: "admin",
    phone: "+357 25 000000",
    country: "Cyprus",
    avatar: "",
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: "proj_001",
    client_id: "user_1",
    client_name: "Alexander Weber",
    project_name: "Paphos Villa — Airbnb Ready Transformation",
    property_location: "Paphos, Cyprus",
    property_type: "Villa",
    purchase_status: "Owned",
    target_use: "Holiday Rental (Airbnb)",
    current_phase: "execution",
    overall_progress_percent: 42,
    budget_status: "on_budget",
    timeline_status: "on_track",
    approved_budget: 60000,
    committed_spend: 44000,
    paid_amount: 28500,
    forecast_final: 58200,
    next_site_visit: "2026-05-14",
    created_at: "2026-02-01T09:00:00Z",
    updated_at: "2026-05-06T14:30:00Z",
    cover_image:
      "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800&q=80",
  },
  {
    id: "proj_002",
    client_id: "user_1",
    client_name: "Alexander Weber",
    project_name: "Limassol Sea View Apartment — Rental Upgrade",
    property_location: "Limassol, Cyprus",
    property_type: "Apartment",
    purchase_status: "Owned",
    target_use: "Short-term Rental",
    current_phase: "handover",
    overall_progress_percent: 96,
    budget_status: "watch",
    timeline_status: "on_track",
    approved_budget: 24000,
    committed_spend: 23400,
    paid_amount: 21740,
    forecast_final: 23800,
    next_site_visit: "2026-05-16",
    created_at: "2025-11-10T10:00:00Z",
    updated_at: "2026-05-05T10:00:00Z",
    cover_image:
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80",
  },
];

export const MOCK_WEEKLY_REPORTS: WeeklyReport[] = [
  {
    id: "rep_001",
    project_id: "proj_001",
    week_number: 11,
    report_date: "2026-05-06",
    phase: "execution",
    overall_progress_percent: 42,
    budget_status: "on_budget",
    timeline_status: "on_track",
    executive_summary:
      "Week 11 confirms solid progress across all active trades. Bathroom wet works are 80% complete; tiling commences Thursday. Kitchen demolition is concluded and new unit installation begins Monday. Electrical first-fix is complete in all rooms. Project remains on budget and on schedule. One quality control issue was detected and corrected before any cost impact occurred. One owner decision is required regarding the limestone floor tile selection before end of week.",
    completed_this_week: [
      "Bathroom waterproofing layer 2 applied and tested (72h cure confirmed)",
      "Kitchen demolition fully completed, debris removed",
      "Electrical first-fix completed in all 4 rooms",
      "Exterior render patch completed (2 sections)",
      "Pool area old tile removal completed",
      "Master bedroom floor screed levelled and dried",
    ],
    in_progress: [
      "Bathroom tiling (starting Thursday, 3 days estimated)",
      "Kitchen unit delivery — confirmed for Monday",
      "Plumbing rough-in — 60% complete",
      "Pool area tile selection — awaiting owner approval",
      "Outdoor lighting cabling — in progress",
    ],
    issues_and_prevented_mistakes: [
      {
        id: "iss_001",
        project_id: "proj_001",
        title: "Incorrect Tile Slope — Bathroom Shower Area",
        description:
          "Site inspection on Tuesday revealed the screed slope in the shower area was set at 0.8% instead of the specified 2%. This would have caused standing water and long-term drainage failure.",
        severity: "high",
        status: "resolved",
        detected_by: "TECTA Site Review",
        responsible_party: "Plaster / Wet Works Contractor",
        risk_if_ignored:
          "Chronic standing water, mould development, potential structural moisture penetration within 12-18 months.",
        recommended_correction: "Full re-screed of shower base to correct 2% fall.",
        prevented_cost: "Estimated €3,200–€5,500 future remediation avoided",
        detected_at: "2026-04-30T10:00:00Z",
        resolved_at: "2026-05-02T16:00:00Z",
      },
    ],
    quality_control_notes: [
      {
        category: "Waterproofing",
        status: "approved",
        note: "Layer 2 waterproofing approved after 72h cure test — no moisture penetration detected.",
      },
      {
        category: "Electrical First-Fix",
        status: "approved",
        note: "All outlet positions cross-checked against kitchen plan and lighting layout. Confirmed correct.",
      },
      {
        category: "Screed Level",
        status: "approved",
        note: "Master bedroom screed laser-checked — tolerance within spec at ±2mm across 6m.",
      },
    ],
    owner_actions_required: [
      {
        id: "oa_001",
        title: "Final Limestone Floor Tile Selection",
        description:
          "Two options remain for the living room / hallway floor tile. Option A: warm limestone-look porcelain 90x90 (recommended by TECTA). Option B: large format travertine 120x60. Cost difference: +€1,800 for Option B. Decision required before tile order is placed Friday.",
        deadline: "2026-05-09",
        cost_impact: "+€0 (A) or +€1,800 (B)",
        timeline_impact: "No delay if decided by Friday EOD",
        status: "pending",
      },
    ],
    next_week_plan: [
      "Bathroom tiling completion (Thursday–Saturday)",
      "Kitchen unit installation (Monday–Wednesday)",
      "Plumbing second-fix start",
      "Floor tile order placed once owner decision received",
      "Outdoor lighting fixtures installation",
      "Pool area new tile installation (start pending approval)",
    ],
    photos: [
      {
        id: "ph_001",
        url: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=600&q=80",
        caption: "Bathroom waterproofing completed — layer 2 applied",
        category: "Bathroom",
        uploaded_at: "2026-05-05T14:00:00Z",
      },
      {
        id: "ph_002",
        url: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=80",
        caption: "Kitchen demolition complete — ready for unit installation",
        category: "Kitchen",
        uploaded_at: "2026-05-04T11:00:00Z",
      },
      {
        id: "ph_003",
        url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=600&q=80",
        caption: "Electrical first-fix — all outlets confirmed against plan",
        category: "Electrical",
        uploaded_at: "2026-05-03T16:00:00Z",
      },
    ],
    created_by: "user_2",
  },
];

export const MOCK_ISSUES: Issue[] = [
  {
    id: "iss_001",
    project_id: "proj_001",
    title: "Incorrect Tile Slope — Bathroom Shower",
    description:
      "Screed slope at 0.8% instead of specified 2%. Corrected before tiling commenced.",
    severity: "high",
    status: "resolved",
    detected_by: "TECTA Site Review",
    responsible_party: "Wet Works Contractor",
    risk_if_ignored: "Standing water, mould, structural moisture damage",
    recommended_correction: "Full re-screed to achieve 2% fall",
    prevented_cost: "€3,200–€5,500",
    detected_at: "2026-04-30T10:00:00Z",
    resolved_at: "2026-05-02T16:00:00Z",
  },
  {
    id: "iss_002",
    project_id: "proj_001",
    title: "Wrong Exterior Tile Batch Delivered",
    description:
      "Tile batch delivered for pool terrace had 5% colour variance from approved sample. Batch rejected and replacement ordered.",
    severity: "medium",
    status: "in_progress",
    detected_by: "TECTA Material Review",
    responsible_party: "Tile Supplier",
    risk_if_ignored: "Visible colour inconsistency across terrace area",
    prevented_cost: "€800–€1,200 rework avoided",
    detected_at: "2026-05-01T09:00:00Z",
  },
  {
    id: "iss_003",
    project_id: "proj_001",
    title: "Electrical Outlet Position Mismatch",
    description:
      "Two kitchen electrical outlets marked on drawing conflicted with kitchen unit placement. Repositioned before first-fix was completed.",
    severity: "medium",
    status: "resolved",
    detected_by: "TECTA Cross-Check",
    responsible_party: "Electrical Contractor",
    risk_if_ignored: "Outlets blocked by kitchen units — unusable",
    prevented_cost: "€600–€900 future relocation avoided",
    detected_at: "2026-04-28T14:00:00Z",
    resolved_at: "2026-04-29T17:00:00Z",
  },
  {
    id: "iss_004",
    project_id: "proj_001",
    title: "Waterproofing Clarification Required",
    description:
      "Contractor proposed skipping second waterproofing membrane layer in the bathroom floor junction. TECTA required full specification compliance.",
    severity: "critical",
    status: "resolved",
    detected_by: "TECTA Site Review",
    responsible_party: "Wet Works Contractor",
    risk_if_ignored: "Bathroom leak to floor below, structural water damage",
    prevented_cost: "€8,000–€15,000 remediation avoided",
    detected_at: "2026-04-22T11:00:00Z",
    resolved_at: "2026-04-24T15:00:00Z",
  },
];

export const MOCK_MATERIAL_BOARDS: MaterialBoard[] = [
  {
    id: "mb_001",
    project_id: "proj_001",
    board_version: 2,
    status: "pending_approval",
    style_direction: "Mediterranean Modern",
    created_at: "2026-04-15T10:00:00Z",
    updated_at: "2026-04-28T16:00:00Z",
    items: [
      {
        id: "mi_001",
        category: "Bodenfliese",
        name: "Warmer Kalkstein-Look Feinsteinzeug 90×90",
        description:
          "Warmer Kalkstein-Look, 90×90 cm, matter rutschhemmender Belag. Geeignet für alle Innenbereiche inkl. Küche und Bad.",
        technical_note: "R10 Rutschhemmung. Frostbeständig. 8mm Stärke.",
        color_hex: "#C8B99A",
        texture_image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80",
        supplier: "Porcelanosa / Equivalent",
        cost_class: "mid",
        approval_status: "approved",
      },
      {
        id: "mi_002",
        category: "Küchenfronten",
        name: "Warmes Eichenfurnier + Mattes Cremeweiß",
        description:
          "Zweifarbige Küche: Unterschränke in warmem Eichenfurnier, Oberschränke in mattem Cremeweiß-Lack. J-Pull-Profilgriffleiste.",
        technical_note: "Soft-Close-Scharniere. Eichenfurnier A-Klasse FSC-zertifiziert.",
        color_hex: "#A07850",
        texture_image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&q=80",
        supplier: "Häcker / Leicht / Equivalent",
        cost_class: "premium",
        approval_status: "pending_approval",
      },
      {
        id: "mi_003",
        category: "Arbeitsplatte",
        name: "Heller Quarzstein — Calacatta-Look",
        description:
          "Heller Calacatta-Look Quarzkomposit, 20mm Stärke, abgerundete Kante.",
        technical_note: "Silestone oder gleichwertig. Hitze- und fleckenbeständig.",
        color_hex: "#F0ECE4",
        texture_image: "https://images.unsplash.com/photo-1556909172-54557c7e4fb7?w=400&q=80",
        supplier: "Silestone / Caesarstone",
        cost_class: "premium",
        approval_status: "approved",
      },
      {
        id: "mi_004",
        category: "Wandfarbe",
        name: "Warmes Mineralweiß — Innenbereich",
        description:
          "Mineralbasierte Farbe in warmem Weißton. Leicht warmer Unterton, kein Kaltweiß.",
        technical_note:
          "Atmungsaktive Silikatfarbe. LRV 88. Geeignet für alle Innenwände.",
        color_hex: "#F8F4EE",
        texture_image: "https://images.unsplash.com/photo-1562259929-b4e1fd3aef09?w=400&q=80",
        supplier: "Keim / Caparol",
        cost_class: "mid",
        approval_status: "approved",
      },
      {
        id: "mi_005",
        category: "Beleuchtung",
        name: "Schwarze Minimal-Spots, 3000K Warmweiß",
        description:
          "Schwarz pulverbeschichteter, schwenkbarer Deckenspot. 3000K Farbtemperatur für wohnliche Atmosphäre.",
        technical_note:
          "IP44 für Badbereich. Dimmbar. Kompatibel mit Casambi-System.",
        color_hex: "#1A1A1A",
        texture_image: "https://images.unsplash.com/photo-1534349762230-e0cadf78f5da?w=400&q=80",
        supplier: "Flos / Artemide / Equivalent",
        cost_class: "premium",
        approval_status: "approved",
      },
      {
        id: "mi_006",
        category: "Badfliese",
        name: "Großformat Warmgrau — 60×120",
        description:
          "Warmgraue Keramik im Großformat, 60×120 cm, strukturierte Oberfläche. Ruhige, spa-ähnliche Atmosphäre.",
        technical_note: "Book-matched Muster möglich. R10 Bodenvariante verfügbar.",
        color_hex: "#9E9890",
        texture_image: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=400&q=80",
        supplier: "Marazzi / Florim",
        cost_class: "premium",
        approval_status: "pending_approval",
      },
      {
        id: "mi_007",
        category: "Außenverkleidung",
        name: "Naturkalkstein-Verkleidung — Außenakzent",
        description:
          "Gespalten-Naturkalksteinplatten für Außenakzentwände. Warme Ocker-Beigetöne.",
        technical_note: "Wetterversiegelt. 40mm Plattenstärke. Frostbeständig.",
        color_hex: "#C4A97D",
        texture_image: "https://images.unsplash.com/photo-1518709766631-a6a7f45921c3?w=400&q=80",
        supplier: "Stoneworld / Local Supplier",
        cost_class: "luxury",
        approval_status: "draft",
      },
      {
        id: "mi_008",
        category: "Terrassenfliese",
        name: "Travertin-Look Feinsteinzeug — Terrasse 80×80",
        description:
          "Großformat Außenporzellan im Travertin-Look, 80×80 cm. Rutschhemmend für Pool- und Terrassenbereiche.",
        technical_note: "R11 Rutschhemmung. UV-beständig. Frostbeständig.",
        color_hex: "#D4BC96",
        texture_image: "https://images.unsplash.com/photo-1596436021236-89e7f79da0f0?w=400&q=80",
        supplier: "Casalgrande Padana / Equivalent",
        cost_class: "mid",
        approval_status: "approved",
      },
    ],
  },
];

export const MOCK_BUDGET_ITEMS: BudgetItem[] = [
  {
    id: "bi_001",
    project_id: "proj_001",
    category: "Demolition",
    planned_amount: 3500,
    quoted_amount: 3200,
    approved_amount: 3200,
    paid_amount: 3200,
    variance: -300,
    status: "within_budget",
  },
  {
    id: "bi_002",
    project_id: "proj_001",
    category: "Plumbing",
    planned_amount: 8000,
    quoted_amount: 7800,
    approved_amount: 7800,
    paid_amount: 4200,
    variance: -200,
    status: "within_budget",
  },
  {
    id: "bi_003",
    project_id: "proj_001",
    category: "Electrical",
    planned_amount: 6500,
    quoted_amount: 6200,
    approved_amount: 6200,
    paid_amount: 3800,
    variance: -300,
    status: "within_budget",
  },
  {
    id: "bi_004",
    project_id: "proj_001",
    category: "Bathroom",
    planned_amount: 12000,
    quoted_amount: 11400,
    approved_amount: 11400,
    paid_amount: 5700,
    variance: -600,
    status: "within_budget",
  },
  {
    id: "bi_005",
    project_id: "proj_001",
    category: "Kitchen",
    planned_amount: 14000,
    quoted_amount: 13600,
    approved_amount: 13600,
    paid_amount: 0,
    variance: -400,
    status: "within_budget",
  },
  {
    id: "bi_006",
    project_id: "proj_001",
    category: "Flooring",
    planned_amount: 7500,
    quoted_amount: 8200,
    approved_amount: 8200,
    paid_amount: 0,
    variance: 700,
    status: "watch",
  },
  {
    id: "bi_007",
    project_id: "proj_001",
    category: "Painting",
    planned_amount: 3000,
    quoted_amount: 2800,
    approved_amount: 2800,
    paid_amount: 0,
    variance: -200,
    status: "within_budget",
  },
  {
    id: "bi_008",
    project_id: "proj_001",
    category: "Terrace / Exterior",
    planned_amount: 5000,
    quoted_amount: 4900,
    approved_amount: 4900,
    paid_amount: 1600,
    variance: -100,
    status: "within_budget",
  },
  {
    id: "bi_009",
    project_id: "proj_001",
    category: "Contingency",
    planned_amount: 6000,
    quoted_amount: 6000,
    approved_amount: 6000,
    paid_amount: 0,
    variance: 0,
    status: "within_budget",
  },
];

export const MOCK_DOCUMENTS: Document[] = [
  {
    id: "doc_001",
    project_id: "proj_001",
    type: "vision_board",
    title: "TECTA Vision Board V1 — Mediterranean Modern",
    uploaded_by: "TECTA Admin",
    file_url: "#",
    file_size: "4.2 MB",
    created_at: "2026-02-15T10:00:00Z",
  },
  {
    id: "doc_002",
    project_id: "proj_001",
    type: "material_spec",
    title: "Material & Finish Specification Board V2",
    uploaded_by: "TECTA Admin",
    file_url: "#",
    file_size: "2.8 MB",
    created_at: "2026-03-01T10:00:00Z",
  },
  {
    id: "doc_003",
    project_id: "proj_001",
    type: "quote",
    title: "Plumbing Quote — Antoniou Plumbing Works",
    uploaded_by: "TECTA Admin",
    file_url: "#",
    file_size: "0.4 MB",
    created_at: "2026-03-10T10:00:00Z",
  },
  {
    id: "doc_004",
    project_id: "proj_001",
    type: "quote",
    title: "Electrical Quote — Kyriakides Electric",
    uploaded_by: "TECTA Admin",
    file_url: "#",
    file_size: "0.3 MB",
    created_at: "2026-03-10T10:00:00Z",
  },
  {
    id: "doc_005",
    project_id: "proj_001",
    type: "weekly_report",
    title: "Weekly Report — Week 11 — 06 May 2026",
    uploaded_by: "TECTA Admin",
    file_url: "#",
    file_size: "1.8 MB",
    created_at: "2026-05-06T18:00:00Z",
  },
  {
    id: "doc_006",
    project_id: "proj_001",
    type: "contract",
    title: "TECTA Renovision Service Agreement",
    uploaded_by: "TECTA Admin",
    file_url: "#",
    file_size: "0.6 MB",
    created_at: "2026-02-05T10:00:00Z",
  },
];

export const MOCK_APPROVALS: Approval[] = [
  {
    id: "ap_001",
    project_id: "proj_001",
    item_type: "material",
    item_id: "mi_002",
    title: "Kitchen Front Material — Oak Veneer + Matte Off-White",
    description:
      "Final selection for kitchen unit fronts. Lower units: warm oak veneer. Upper units: matte off-white lacquer. Handleless J-pull profile. Soft-close hinges throughout.",
    cost_impact: "Included in approved kitchen budget (€13,600)",
    timeline_impact: "6-week lead time — order required by 12 May",
    status: "pending",
    deadline: "2026-05-12",
    files: [],
  },
  {
    id: "ap_002",
    project_id: "proj_001",
    item_type: "material",
    item_id: "mi_006",
    title: "Bathroom Wall Tile — Large Format Warm Grey 60×120",
    description:
      "Proposed bathroom wall tile: warm grey large format ceramic, 60×120 cm. Structured surface. Creates calm spa atmosphere consistent with TECTA vision board.",
    cost_impact: "Included in bathroom budget",
    timeline_impact: "2-week delivery, no delay if ordered this week",
    status: "pending",
    deadline: "2026-05-10",
    files: [],
  },
  {
    id: "ap_003",
    project_id: "proj_001",
    item_type: "floor_tile",
    item_id: "floor_tile_01",
    title: "Living Room / Hallway Floor Tile Final Selection",
    description:
      "Choose between two options: Option A — Warm limestone-look porcelain 90×90 (TECTA recommended, no price change). Option B — Large format travertine 120×60 (+€1,800 to budget, more premium look).",
    cost_impact: "Option A: €0 change. Option B: +€1,800",
    timeline_impact: "Order must be placed by Friday 09 May to avoid delay",
    status: "pending",
    deadline: "2026-05-09",
    files: [],
  },
];

export const MOCK_QUOTES: ContractorQuote[] = [
  {
    id: "cq_001",
    project_id: "proj_001",
    contractor_name: "Antoniou Plumbing Works",
    trade: "Plumbing",
    quote_amount: 7800,
    scope_included: [
      "Full bathroom re-plumb",
      "Kitchen plumbing connection",
      "New waste runs to 3 bathrooms",
      "Thermostatic shower valves supply & install",
    ],
    scope_excluded: ["Sanitary fittings (supply only)", "Tile works"],
    status: "recommended",
    recommendation:
      "Recommended. Competitive price, complete scope, 3 successful prior projects reviewed.",
    risk_notes: "None identified. Full scope submitted, references verified.",
    reviewed_by_tecta: "TECTA Admin",
  },
  {
    id: "cq_002",
    project_id: "proj_001",
    contractor_name: "Paphos Plumbing Solutions",
    trade: "Plumbing",
    quote_amount: 9400,
    scope_included: [
      "Full bathroom re-plumb",
      "Kitchen plumbing",
      "Waste runs",
    ],
    scope_excluded: [
      "Thermostatic valves",
      "Sanitary fittings",
      "Tile works",
      "Any hot water work",
    ],
    status: "rejected",
    recommendation:
      "Not recommended. Higher price with narrower scope. Thermostatic valves excluded — scope gap.",
    risk_notes:
      "Scope gaps require careful monitoring. Hot water exclusion creates coordination risk.",
    reviewed_by_tecta: "TECTA Admin",
  },
  {
    id: "cq_003",
    project_id: "proj_001",
    contractor_name: "Kyriakides Electric",
    trade: "Electrical",
    quote_amount: 6200,
    scope_included: [
      "Full electrical rewire",
      "Distribution board upgrade",
      "First and second fix",
      "External lighting cabling",
      "Air conditioning pre-wiring",
    ],
    scope_excluded: ["Fixture supply", "A/C units"],
    status: "approved",
    recommendation: "Approved by owner. Strong scope, competitive price.",
    risk_notes: "None. TECTA cross-checked outlet positions against kitchen plan.",
    reviewed_by_tecta: "TECTA Admin",
  },
];

export const MOCK_ROOM_MATERIAL_BOARDS: RoomMaterialBoard[] = [
  {
    id: "rmb_001",
    project_id: "proj_001",
    board_version: 2,
    status: "pending_approval",
    style_direction: "Mediterranean Modern",
    created_at: "2026-04-15T10:00:00Z",
    updated_at: "2026-04-28T16:00:00Z",
    rooms: [
      {
        id: "room_k",
        name: "Küche",
        emoji: "🍳",
        area_sqm: 18,
        current_photo: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80",
        surfaces: [
          {
            id: "surf_k_1",
            name: "Bodenfliese",
            placement: "floor",
            selected_option_id: "opt_k_1_a",
            approval_status: "approved",
            options: [
              {
                id: "opt_k_1_a",
                name: "Kalkstein-Look 90×90",
                description: "Warmer Kalkstein-Look, 90×90 cm, matte anti-slip Oberfläche. Für alle Innenbereiche geeignet.",
                texture_image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80",
                color_hex: "#C8B99A",
                supplier: "Porcelanosa",
                cost_class: "mid",
                technical_note: "R10 Rutschhemmung. 8mm Stärke. Frostbeständig.",
                price_per_sqm: 48,
                ai_result_image: "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80",
              },
              {
                id: "opt_k_1_b",
                name: "Terrakotta-Look 60×60",
                description: "Warmer Terrakotta-Ton, 60×60 cm. Mediterrane Ausstrahlung, zeitlos.",
                texture_image: "https://images.unsplash.com/photo-1596436021236-89e7f79da0f0?w=400&q=80",
                color_hex: "#C07850",
                supplier: "Marazzi",
                cost_class: "budget",
                price_per_sqm: 32,
                ai_result_image: "https://images.unsplash.com/photo-1556909172-54557c7e4fb7?w=800&q=80",
              },
              {
                id: "opt_k_1_c",
                name: "Schiefer-Look Dunkelgrau 60×120",
                description: "Graphitgrauer Schiefer-Look, 60×120 cm. Elegante, ruhige Wirkung.",
                texture_image: "https://images.unsplash.com/photo-1574180566232-aaad1b5b8450?w=400&q=80",
                color_hex: "#4A4A4A",
                supplier: "Florim",
                cost_class: "premium",
                price_per_sqm: 65,
                ai_result_image: "https://images.unsplash.com/photo-1556909172-54557c7e4fb7?w=800&q=80",
              },
            ],
          },
          {
            id: "surf_k_2",
            name: "Fliesenspiegel",
            placement: "wall",
            selected_option_id: "opt_k_2_a",
            approval_status: "approved",
            options: [
              {
                id: "opt_k_2_a",
                name: "Weißes Subway Tile 10×30",
                description: "Klassisches weißes Subway Tile, 10×30 cm. Zeitlos, hell und pflegeleicht.",
                texture_image: "https://images.unsplash.com/photo-1600607686527-6fb886090705?w=400&q=80",
                color_hex: "#F5F5F5",
                supplier: "Equipe",
                cost_class: "budget",
                price_per_sqm: 28,
                ai_result_image: "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80",
              },
              {
                id: "opt_k_2_b",
                name: "Travertin-Look 30×60",
                description: "Warm-beiger Travertin-Look, 30×60 cm. Mediterrane Eleganz für die Küchenwand.",
                texture_image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80",
                color_hex: "#D4BC96",
                supplier: "Casalgrande Padana",
                cost_class: "mid",
                price_per_sqm: 42,
                ai_result_image: "https://images.unsplash.com/photo-1556909172-54557c7e4fb7?w=800&q=80",
              },
            ],
          },
          {
            id: "surf_k_3",
            name: "Küchenfronten",
            placement: "fronts",
            selected_option_id: "opt_k_3_a",
            approval_status: "pending_approval",
            options: [
              {
                id: "opt_k_3_a",
                name: "Eiche natur + Cremeweiß matt",
                description: "Zweifarbige Küche: Unterschränke Eichenfurnier, Oberschränke Cremeweiß-Lack. Handleless J-Pull.",
                texture_image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&q=80",
                color_hex: "#A07850",
                supplier: "Häcker / Leicht",
                cost_class: "premium",
                technical_note: "Soft-Close-Scharniere. Eichenfurnier A-Klasse FSC.",
                ai_result_image: "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80",
              },
              {
                id: "opt_k_3_b",
                name: "Anthrazit Hochglanz + Weiß matt",
                description: "Moderne Kombination: Anthrazit-Hochglanz unten, Weiß-matt oben. Grifflos.",
                texture_image: "https://images.unsplash.com/photo-1556909172-54557c7e4fb7?w=400&q=80",
                color_hex: "#2D2D2D",
                supplier: "SieMatic / Nolte",
                cost_class: "premium",
                ai_result_image: "https://images.unsplash.com/photo-1556909172-54557c7e4fb7?w=800&q=80",
              },
            ],
          },
        ],
      },
      {
        id: "room_b",
        name: "Bad",
        emoji: "🚿",
        area_sqm: 9,
        current_photo: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800&q=80",
        surfaces: [
          {
            id: "surf_b_1",
            name: "Wandfliese",
            placement: "wall",
            selected_option_id: "opt_b_1_a",
            approval_status: "pending_approval",
            options: [
              {
                id: "opt_b_1_a",
                name: "Warmgrau Large Format 60×120",
                description: "Warmgraues Großformat, 60×120 cm, strukturierte Oberfläche. Ruhige Spa-Atmosphäre.",
                texture_image: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=400&q=80",
                color_hex: "#9E9890",
                supplier: "Marazzi",
                cost_class: "premium",
                price_per_sqm: 72,
                technical_note: "Book-matched Muster möglich. R10 Bodenvariante verfügbar.",
                ai_result_image: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800&q=80",
              },
              {
                id: "opt_b_1_b",
                name: "Weißer Marmor-Look 60×120",
                description: "Heller Marmor-Look in Weiß-Grau, 60×120 cm. Zeitloser Luxus.",
                texture_image: "https://images.unsplash.com/photo-1600607686527-6fb886090705?w=400&q=80",
                color_hex: "#F0EDE8",
                supplier: "Porcelanosa",
                cost_class: "luxury",
                price_per_sqm: 95,
                ai_result_image: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800&q=80",
              },
              {
                id: "opt_b_1_c",
                name: "Kalkstein-Look 60×60",
                description: "Heller Kalkstein-Look, 60×60 cm. Natürliche, warme Ausstrahlung.",
                texture_image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80",
                color_hex: "#C8B99A",
                supplier: "Florim",
                cost_class: "mid",
                price_per_sqm: 52,
                ai_result_image: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800&q=80",
              },
            ],
          },
          {
            id: "surf_b_2",
            name: "Bodenfliese",
            placement: "floor",
            selected_option_id: "opt_b_2_a",
            approval_status: "approved",
            options: [
              {
                id: "opt_b_2_a",
                name: "Warmgrau Anti-Slip 60×60",
                description: "Passend zur Wandfliese, R10 Anti-Slip Nassbereich. Koordiniert mit Wandfliese.",
                texture_image: "https://images.unsplash.com/photo-1574180566232-aaad1b5b8450?w=400&q=80",
                color_hex: "#9E9890",
                supplier: "Marazzi",
                cost_class: "premium",
                price_per_sqm: 68,
                ai_result_image: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800&q=80",
              },
              {
                id: "opt_b_2_b",
                name: "Weiß Mosaik 5×5",
                description: "Klassisches weißes Mosaik, 5×5 cm. Zeitlos, auf Netz verlegt.",
                texture_image: "https://images.unsplash.com/photo-1600607686527-6fb886090705?w=400&q=80",
                color_hex: "#F5F5F5",
                supplier: "Agrob Buchtal",
                cost_class: "mid",
                price_per_sqm: 55,
                ai_result_image: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800&q=80",
              },
            ],
          },
        ],
      },
      {
        id: "room_w",
        name: "Wohnzimmer",
        emoji: "🛋️",
        area_sqm: 35,
        current_photo: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
        surfaces: [
          {
            id: "surf_w_1",
            name: "Bodenbelag",
            placement: "floor",
            selected_option_id: "opt_w_1_a",
            approval_status: "approved",
            options: [
              {
                id: "opt_w_1_a",
                name: "Eiche-Dielen hell gebürstet",
                description: "Helles Eichenparkett, gebürstet, Landhausdielen 20×180 cm. Warm und hochwertig.",
                texture_image: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=400&q=80",
                color_hex: "#C8A870",
                supplier: "Barlinek / Kahrs",
                cost_class: "premium",
                price_per_sqm: 85,
                ai_result_image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
              },
              {
                id: "opt_w_1_b",
                name: "Warmgrau Feinsteinzeug 120×120",
                description: "Warmer Grauton im Großformat, 120×120 cm. Modern und pflegeleicht.",
                texture_image: "https://images.unsplash.com/photo-1574180566232-aaad1b5b8450?w=400&q=80",
                color_hex: "#8A8882",
                supplier: "Florim",
                cost_class: "mid",
                price_per_sqm: 55,
                ai_result_image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
              },
            ],
          },
          {
            id: "surf_w_2",
            name: "Wandfarbe",
            placement: "wall",
            selected_option_id: "opt_w_2_a",
            approval_status: "pending_approval",
            options: [
              {
                id: "opt_w_2_a",
                name: "Warmes Mineralweiß",
                description: "LRV 88, leicht warmer Unterton. Kein Kaltweiß. Alle Innenwände.",
                texture_image: "https://images.unsplash.com/photo-1562259929-b4e1fd3aef09?w=400&q=80",
                color_hex: "#F8F4EE",
                supplier: "Keim Purkristalat",
                cost_class: "mid",
                ai_result_image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
              },
              {
                id: "opt_w_2_b",
                name: "Zartes Greige",
                description: "Warmes Greige — zwischen Beige und Grau. Zeitgemäß und harmonisch.",
                color_hex: "#D4C9B8",
                supplier: "Caparol",
                cost_class: "budget",
                ai_result_image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
              },
              {
                id: "opt_w_2_c",
                name: "Navy Akzentwand",
                description: "Eine Wand in tiefem Navy #0B1F33. Dramatischer Kontrast zum hellen Boden.",
                color_hex: "#0B1F33",
                supplier: "Farrow & Ball",
                cost_class: "premium",
                ai_result_image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
              },
            ],
          },
        ],
      },
      {
        id: "room_t",
        name: "Terrasse",
        emoji: "🌿",
        area_sqm: 28,
        current_photo: "https://images.unsplash.com/photo-1599809275671-b5942cabc7a2?w=800&q=80",
        surfaces: [
          {
            id: "surf_t_1",
            name: "Terrassenfliese",
            placement: "floor",
            selected_option_id: "opt_t_1_a",
            approval_status: "approved",
            options: [
              {
                id: "opt_t_1_a",
                name: "Travertin-Look Porzellan 80×80",
                description: "Großformat Außenporzellan im Travertin-Look, 80×80 cm. R11 Anti-Slip, UV-beständig.",
                texture_image: "https://images.unsplash.com/photo-1596436021236-89e7f79da0f0?w=400&q=80",
                color_hex: "#D4BC96",
                supplier: "Casalgrande Padana",
                cost_class: "mid",
                price_per_sqm: 45,
                ai_result_image: "https://images.unsplash.com/photo-1599809275671-b5942cabc7a2?w=800&q=80",
              },
              {
                id: "opt_t_1_b",
                name: "Anthrazit Beton-Look 60×60",
                description: "Moderner Beton-Look in Anthrazit, 60×60 cm. R11 Anti-Slip. Zeitgemäß.",
                texture_image: "https://images.unsplash.com/photo-1574180566232-aaad1b5b8450?w=400&q=80",
                color_hex: "#3A3A3A",
                supplier: "Florim",
                cost_class: "mid",
                price_per_sqm: 42,
                ai_result_image: "https://images.unsplash.com/photo-1599809275671-b5942cabc7a2?w=800&q=80",
              },
            ],
          },
          {
            id: "surf_t_2",
            name: "Sichtschutz",
            placement: "wall",
            approval_status: "draft",
            options: [
              {
                id: "opt_t_2_a",
                name: "Bambus-Look Composite-Lamellen",
                description: "Naturoptik-Composite, wartungsfrei, UV-beständig, Zypern-Klima geprüft.",
                color_hex: "#A07840",
                supplier: "Cedral",
                cost_class: "mid",
              },
              {
                id: "opt_t_2_b",
                name: "Anthrazit Aluminium-Lamellen",
                description: "Gebürstetes Aluminium, pulverbeschichtet in Anthrazit. Langlebig und modern.",
                color_hex: "#2D2D2D",
                supplier: "Schörghuber",
                cost_class: "premium",
              },
            ],
          },
        ],
      },
    ],
  },
];
